#!/bin/sh
# postrm script for kannel
#
# see: dh_installdeb(1)

set -e

case "$1" in
remove|upgrade|failed-upgrade|abort-upgrade|disappear|abort-install)
  ;;
purge)
  rm -rf /var/log/kannel /var/run/kannel
  if [ -d /etc/kannel ]; then
    rmdir /etc/kannel || true
  fi
  userdel kannel >/dev/null 2>&1 || true
  ;;
*)
  echo "postrm called with unknown argument '$1'" >&2
  exit 1
esac

#DEBHELPER#

exit 0
