#
# Sample configuration file for Kannel bearerbox on Debian.
# See the documentation for explanations of fields.
#

# HTTP administration is enabled by default only for localhost and any local
# address for the /usr/libexec/kannel-bearerbox-waiter probe. Make sure you
# set a proper password if you enable it for anything other than localhost.

group = core
admin-interface = lo
admin-port = 13000
admin-password = bar
admin-deny-ip = "*.*.*.*"
admin-allow-ip = "127.0.0.1"
wapbox-port = 13002
wdp-interface-name = "*"
log-file = "/var/log/kannel/bearerbox.log"
box-deny-ip = "*.*.*.*"
box-allow-ip = "127.0.0.1"

group = wapbox
bearerbox-host = localhost
log-file = "/var/log/kannel/wapbox.log"
